// Curated list of drawable words - filtered to remove abstract concepts
// and include only concrete, visual objects/actions that are fun to draw

export const drawableWords = [
  // Animals
  "ant", "bat", "bee", "cat", "cow", "dog", "eel", "emu", "fox", "fly",
  "bear", "bird", "boar", "bull", "crab", "crow", "deer", "duck", "fish",
  "frog", "goat", "hawk", "lion", "mole", "moth", "panda", "parrot", "penguin",
  "pig", "rat", "seal", "sheep", "snail", "snake", "spider", "squid", "tiger",
  "toad", "whale", "wolf", "zebra", "camel", "cheetah", "chicken", "dolphin",
  "dragon", "elephant", "giraffe", "gorilla", "hamster", "hippo", "jaguar",
  "kangaroo", "leopard", "lobster", "monkey", "octopus", "ostrich", "otter",
  "peacock", "pelican", "pigeon", "poodle", "rabbit", "raccoon", "rhino",
  "rooster", "shark", "shrimp", "sloth", "sparrow", "turtle", "unicorn",
  "walrus", "worm", "dinosaur", "hedgehog", "koala", "moose", "porcupine",
  "reindeer", "salamander", "seagull", "starfish",
  
  // Food & Drinks
  "ham", "pie", "tea", "beef", "beer", "cake", "cola", "corn", "crab",
  "egg", "fish", "meat", "milk", "nuts", "oreo", "pear", "plum", "pork",
  "rice", "roll", "salt", "soup", "stew", "sushi", "taco", "waffle", "bacon",
  "bagel", "bread", "candy", "carrot", "cheese", "cherry", "chips", "cookie",
  "cream", "curry", "donut", "fries", "fruit", "grape", "honey", "jelly",
  "lemon", "mango", "melon", "olive", "onion", "pasta", "peach", "peanut",
  "pepper", "pickle", "pizza", "popcorn", "potato", "pretzel", "pumpkin",
  "radish", "salad", "sauce", "shrimp", "snack", "steak", "sugar", "toast",
  "tomato", "burger", "burrito", "butter", "coffee", "cupcake", "garlic",
  "hotdog", "icecream", "ketchup", "lasagna", "lettuce", "lobster", "muffin",
  "mushroom", "noodles", "oatmeal", "pancake", "pineapple", "popcorn",
  "sandwich", "sausage", "spaghetti", "spinach", "strawberry", "tuna",
  "waffle", "watermelon", "yogurt",
  
  // Body Parts
  "arm", "ear", "eye", "toe", "chin", "claw", "face", "foot", "hand",
  "head", "heel", "knee", "nail", "neck", "nose", "palm", "skin", "thumb",
  "tooth", "ankle", "brain", "cheek", "chest", "elbow", "finger", "muscle",
  "shoulder", "stomach", "tongue", "eyebrow", "eyelash", "forehead",
  
  // Household Objects
  "axe", "bag", "bed", "box", "can", "cap", "cup", "bag", "bar", "bell",
  "belt", "bill", "book", "bowl", "cage", "cane", "cape", "cash", "cell",
  "coin", "comb", "cone", "cord", "cork", "desk", "dice", "dock", "doll",
  "dome", "door", "drum", "fork", "fuse", "gate", "gear", "gift", "globe",
  "glue", "hook", "hose", "iron", "junk", "key", "kite", "lamp", "lens",
  "lock", "mask", "mop", "mug", "nail", "oar", "oven", "pan", "peg", "pen",
  "pipe", "plug", "pole", "pot", "pump", "ring", "rope", "ruby", "safe",
  "saw", "seat", "shed", "sign", "sink", "soap", "sofa", "spear", "spool",
  "stool", "straw", "sword", "table", "tape", "tent", "thread", "throne",
  "tile", "tool", "towel", "tray", "tub", "vase", "wall", "watch", "wax",
  "web", "wheel", "whisk", "wire", "anchor", "anvil", "arrow", "basket",
  "bathtub", "battery", "blanket", "blimp", "bottle", "broom", "brush",
  "bucket", "button", "cabinet", "camera", "candle", "cannon", "carpet",
  "ceiling", "chain", "chair", "chalk", "chimney", "clock", "closet", "comb",
  "couch", "cradle", "crib", "crown", "crutch", "curtain", "cushion", "dagger",
  "desk", "doorbell", "drawer", "drill", "dustpan", "fan", "fence", "flashlight",
  "frame", "fridge", "funnel", "furniture", "garage", "hammer", "hanger",
  "heater", "helmet", "hinge", "ladder", "lantern", "lawnmower", "lighter",
  "lightbulb", "mailbox", "matches", "mattress", "microphone", "mirror",
  "needle", "paint", "paintbrush", "parachute", "pencil", "photograph",
  "picture", "pillow", "pliers", "printer", "purse", "radio", "razor",
  "rifle", "rocket", "roof", "safe", "scale", "scissors", "screw", "screwdriver",
  "shelf", "shield", "shovel", "shutter", "sponge", "spoon", "spotlight",
  "stairs", "stapler", "stove", "suitcase", "swing", "switch", "teapot",
  "telephone", "telescope", "television", "thermostat", "timer", "toolbox",
  "toothbrush", "toothpaste", "torch", "treasure", "trophy", "trumpet",
  "umbrella", "vacuum", "wagon", "wallet", "wardrobe", "washing machine",
  "weapon", "window", "wrench",
  
  // Clothing & Accessories
  "hat", "tie", "boot", "coat", "cuff", "dress", "flip flop", "gown", "heel",
  "hood", "jean", "mask", "mitt", "robe", "scarf", "shirt", "shoe", "shorts",
  "skirt", "sleeve", "slippers", "sock", "suit", "toga", "tutu", "vest",
  "belt", "bikini", "blouse", "bow tie", "bracelet", "button", "cap", "cloak",
  "collar", "costume", "earring", "glasses", "glove", "gown", "jacket",
  "jeans", "jewelry", "necklace", "overalls", "pajamas", "pants", "pocket",
  "purse", "raincoat", "ring", "sandal", "scarf", "shoe", "sneaker", "sunglasses",
  "sweater", "swimsuit", "tie", "tuxedo", "underwear", "uniform", "vest",
  "wig", "zipper",
  
  // Nature & Outdoors
  "ash", "dew", "fog", "ice", "log", "mud", "oak", "ore", "pond", "rock",
  "sand", "seed", "snow", "star", "sun", "tree", "vine", "weed", "wood",
  "bark", "bud", "cave", "clay", "cliff", "coal", "dawn", "dune", "earth",
  "fall", "farm", "fire", "gust", "hail", "heat", "hill", "hole", "island",
  "ivy", "lake", "lava", "lawn", "leaf", "moon", "moss", "oasis", "ocean",
  "path", "peak", "rain", "reef", "river", "root", "rose", "shore", "sky",
  "stem", "stone", "storm", "stream", "sunrise", "sunset", "swamp", "tide",
  "trail", "valley", "wave", "wind", "beach", "branch", "cactus", "canyon",
  "cloud", "comet", "crater", "creek", "crystal", "desert", "diamond",
  "drought", "field", "flame", "flood", "flower", "forest", "fossil", "garden",
  "glacier", "grass", "gravity", "hedge", "iceberg", "jungle", "lightning",
  "meadow", "meteor", "mountain", "mud", "mushroom", "nest", "palm tree",
  "pebble", "planet", "plant", "pond", "quicksand", "rainbow", "rapids",
  "rock", "sand", "shell", "smoke", "snowflake", "soil", "stone", "stream",
  "thunder", "tornado", "treasure", "tulip", "twig", "valley", "volcano",
  "waterfall", "wetland",
  
  // Vehicles & Transportation
  "bmw", "bmx", "bus", "cab", "car", "jet", "ship", "sled", "sub", "taxi",
  "tow", "van", "bike", "boat", "jeep", "kart", "moped", "plane", "raft",
  "tank", "train", "truck", "yacht", "bicycle", "blimp", "canoe", "cart",
  "ferry", "glider", "hovercraft", "kayak", "limo", "motorcycle", "rocket",
  "sailboat", "scooter", "skateboard", "sleigh", "spaceship", "speedboat",
  "submarine", "surfboard", "tractor", "trailer", "tricycle", "wagon",
  
  // Sports & Activities
  "bow", "bat", "ace", "ball", "base", "bowl", "dart", "dive", "flag", "goal",
  "golf", "hoop", "jog", "jump", "kick", "laps", "pool", "puck", "punt",
  "race", "ring", "roll", "rope", "run", "skate", "ski", "sled", "swim",
  "swing", "toss", "trap", "vault", "walk", "baseball", "basketball", "boxing",
  "bowling", "catch", "chess", "cricket", "dance", "darts", "dodge", "fencing",
  "fishing", "football", "frisbee", "hiking", "hockey", "jogging", "karate",
  "marathon", "olympics", "paddleball", "polo", "referee", "rugby", "running",
  "sailing", "skating", "skiing", "soccer", "softball", "sprint", "surfing",
  "swimming", "tennis", "track", "trophy", "volleyball", "weightlifting",
  "wrestling", "yoga",
  
  // Actions & Verbs
  "bite", "boil", "burp", "chew", "clap", "copy", "cut", "dig", "drip", "eat",
  "fall", "bite", "blow", "bounce", "break", "breathe", "brush", "burn",
  "carry", "catch", "climb", "cook", "crawl", "cry", "dance", "draw", "drink",
  "drive", "drop", "dunk", "elbow", "escape", "explode", "faint", "fall",
  "fight", "fire", "fish", "flick", "flip", "flush", "fold", "freeze", "frown",
  "grab", "grill", "hatch", "hide", "hug", "hunt", "itch", "juggle", "jump",
  "kick", "kiss", "kneel", "laugh", "leak", "lick", "lift", "march", "melt",
  "paint", "peck", "peel", "pinch", "plug", "point", "poke", "pour", "pray",
  "pull", "punch", "push", "read", "ride", "roast", "roll", "rub", "run",
  "scratch", "scream", "shake", "shave", "shoot", "shout", "sing", "sit",
  "skate", "sketch", "skip", "slap", "sleep", "slice", "slide", "slip",
  "smell", "smile", "snap", "sneeze", "sniff", "snore", "spit", "splash",
  "spray", "squeeze", "stab", "stamp", "stand", "stare", "stir", "stomp",
  "stretch", "stumble", "suck", "swallow", "sweat", "swim", "swing", "tear",
  "throw", "tickle", "tie", "tip", "toast", "trip", "tug", "turn", "twist",
  "type", "vacuum", "wag", "walk", "wash", "wave", "whisper", "whistle",
  "wink", "wipe", "write", "yawn", "yell",
  
  // Places & Buildings
  "asia", "barn", "cafe", "camp", "cuba", "dock", "dorm", "fiji", "gate",
  "gym", "home", "jail", "mall", "maze", "peru", "pier", "pole", "rome",
  "roof", "shop", "step", "yard", "zoo", "airport", "aquarium", "arcade",
  "arch", "attic", "bakery", "bank", "barn", "basement", "bathroom", "beach",
  "bedroom", "bridge", "building", "cabin", "cafe", "cafeteria", "cage",
  "castle", "cathedral", "cave", "ceiling", "chapel", "chimney", "church",
  "circus", "city", "classroom", "cliff", "clinic", "closet", "cottage",
  "country", "courthouse", "diner", "door", "driveway", "dungeon", "embassy",
  "factory", "fairground", "farm", "fence", "field", "fireplace", "fortress",
  "fountain", "garage", "garden", "gate", "graveyard", "greenhouse", "hallway",
  "harbor", "hospital", "hotel", "house", "igloo", "island", "jail", "kitchen",
  "laboratory", "library", "lighthouse", "mansion", "market", "monument",
  "mosque", "motel", "mountain", "museum", "neighborhood", "observatory",
  "office", "opera house", "palace", "park", "parking lot", "pathway",
  "pharmacy", "pier", "playground", "pool", "porch", "port", "prison",
  "pyramid", "ranch", "restaurant", "road", "roof", "ruins", "runway",
  "school", "shop", "sidewalk", "skyscraper", "stadium", "stairs", "statue",
  "store", "street", "studio", "supermarket", "synagogue", "temple", "tent",
  "theater", "tomb", "tower", "town", "tunnel", "village", "wall", "warehouse",
  "well", "window", "windmill", "yard", "zoo",
  
  // Miscellaneous Drawable Objects
  "flag", "gem", "gift", "gold", "horn", "knot", "lego", "logo", "map",
  "paw", "peg", "pet", "sign", "spot", "scar", "tag", "tail", "trap", "usb",
  "wig", "wing", "yolk", "badge", "balloon", "band", "banner", "barrel",
  "bead", "bell", "blob", "block", "blur", "bomb", "brick", "bubble", "bulb",
  "bump", "buoy", "card", "cartoon", "circle", "clover", "clue", "coil",
  "comic", "cube", "curve", "dart", "diamond", "disk", "doodle", "dot",
  "emoji", "eraser", "explosion", "feather", "film", "fingerprint", "flame",
  "flask", "foam", "frost", "frown", "furniture", "fuse", "handle", "heart",
  "hexagon", "ink", "knob", "label", "lever", "line", "magic", "marble",
  "mark", "medal", "molecule", "net", "number", "octagon", "oval", "package",
  "paddle", "paper", "pattern", "pentagon", "pixel", "plank", "poster",
  "powder", "prism", "puzzle", "rectangle", "ribbon", "ripple", "ruler",
  "scar", "scribble", "scroll", "shadow", "shape", "shard", "shimmer",
  "silhouette", "sketch", "spark", "sparkle", "sphere", "spike", "spiral",
  "splash", "splatter", "splotch", "spore", "spotlight", "spring", "sprinkle",
  "square", "stain", "stamp", "star", "sticker", "sting", "stripe", "stub",
  "stump", "symbol", "target", "texture", "ticket", "triangle", "wand",
  "wedge", "wrinkle", "zigzag",
  
  // Popular Characters & Brands (recognizable)
  "gru", "elmo", "dora", "mario", "pepsi", "sonic", "yoda", "batman",
  "pikachu", "shrek", "spongebob", "barbie", "godzilla", "homer", "joker",
  "luigi", "mickey mouse", "minion", "ninja", "olaf", "patrick", "peter pan",
  "picasso", "pinocchio", "popeye", "robin hood", "scooby doo", "shakespeare",
  "superman", "tarzan", "tinkerbell", "yoshi", "zelda",
];
